### PR TITLE
Added .DS_Store to .gitignore

### PR DESCRIPTION
**Pull request by Gh0stlyy**

### CODE REVIEW

**Comment by Taarek** [comment]
And why?

**Comment by Gh0stlyy** [comment]
Because it is a binary file that gets changed everytime I try to edit a file.

**Comment by AnnsAnns** [comment]
MacOS problems, tss :P

**Comment by Taarek** [comment]
right, i forgot to merge this lol

**Comment by Pheonix5555** [comment]
wow pheonix commenting on closed prs wow

**Pull request merged**
